### ISSUE TITLE
Checking for duplicate row names is broken, test using data_otut.csv

### ISSUE THREAD

**Issue by alekseyenko** [tamilyn/shiny-pesame#8]

**Comment by tamilyn** [comment]
<img width="648" alt="uniq_row_names_issue_8" src="https://user-images.githubusercontent.com/733799/35442543-a19aa544-0275-11e8-9c9d-72db69803131.png">

R requires that row names be unique, so if they are not unique then a warning/explanatory message is displayed.     

Could you be more specific on what is broken and what should be happening?

**Comment by alekseyenko** [comment]
Well they are obviously unique, but I still see the warning. The same file loaded ok previously. Try one of the csv files in the data folder. 
-a

**Comment by tamilyn** [comment]
unique and not na/empty.  The problem in that example is that Use column names needs to be selected because the first row is the column name - look at the first row/column - it's empty.  that is not a valid R row name.

**Comment by tamilyn** [comment]
the file can be loaded, just check "Use column names"

**Comment by alekseyenko** [comment]
I get it now. Thanks. 
-a
